# Assignment 1 - NumPy
**Name: Niyati** 
**Roll No: 102303356** 

## Q1: Questions on Basic NumPy Array

### (a) Reverse the NumPy array:
arr = np.array([1, 2, 3, 6, 4, 5])

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array: ",reversed_arr)

Reversed array:  [5 4 6 3 2 1]


### (b) Flatten the NumPy arr:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

using any two NumPy in-built methods 

In [2]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat1= array1.flatten()
print("Flattened array: ", flat1)

flat2= array1.ravel()
print("Raveled array: ", flat2)

Flattened array:  [1 2 3 2 4 5 1 2 3]
Raveled array:  [1 2 3 2 4 5 1 2 3]


### (c) Compare the following numpy arrays: 
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]]) 

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

equality_check = np.array_equal(arr1, arr2)
print("arr1 and arr2 are equal: ", equality_check)

arr1 and arr2 are equal:  True


### (d) Find the most frequent value and their indice(s) in the following arrays: 
(i) x = np.array([1,2,3,4,5,1,2,1,1,1])

(ii) y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

In [4]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

unique_x, counts_x = np.unique(x, return_counts=True)
unique_y, counts_y = np.unique(y, return_counts=True)

most_frequent_x = unique_x[np.argmax(counts_x)]
indices_x = np.where(x == most_frequent_x)[0]

most_frequent_y = unique_y[np.argmax(counts_y)]
indices_y = np.where(y == most_frequent_y)[0]

print("Most frequent element in x:", most_frequent_x, "at indices:", indices_x)
print("Most frequent element in y:", most_frequent_y, "at indices:", indices_y)

Most frequent element in x: 1 at indices: [0 5 7 8 9]
Most frequent element in y: 1 at indices: [0 1 2]


### (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find:
i. Sum of all elements 

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise 

In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total_sum = np.sum(gfg)
print("Total sum of elements in the matrix:", total_sum)

row_sum = np.sum(gfg, axis=1)
print("Sum of each row:\n", row_sum)

col_sum = np.sum(gfg, axis=0)
print("Sum of each column:", col_sum)

Total sum of elements in the matrix: 45
Sum of each row:
 [[14]
 [16]
 [15]]
Sum of each column: [[20  9 16]]


### (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find:
i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix 

iv. Inverse of matrix

v. Determinant of matrix 

In [7]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

diagonal_sum = np.trace(n_array)
print("Sum of diagonal elements:", diagonal_sum)

eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

inverse_matrix = np.linalg.inv(n_array)
print("Inverse of the matrix:\n", inverse_matrix)

determinant = np.linalg.det(n_array)
print("Determinant of the matrix:", determinant)

Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


### (g) Multiply the following matrices and also find covariance between matrices using NumPy: 
i.  p = [[1, 2], [2, 3]] and q = [[4, 5], [6, 7]] 
    
ii. p = [[1, 2], [2, 3], [4, 5]] and q = [[4, 5, 1], [6, 7, 2]] 

In [17]:
p1 = [[1, 2], [2, 3]] 
q1 = [[4, 5], [6, 7]] 

product1 = np.dot(p1, q1)
print("Product of p1 and q1:\n", product1)
cov1 = np.cov(p1, q1)
print("Covariance matrix of p1 and q1:\n", cov1)
    
# p2 = [[1, 2], [2, 3], [4, 5]]
# q2 = [[4, 5, 1], [6, 7, 2]] 
# product2 = np.dot(p2, q2)
# print("Product of p2 and q2:\n", product2)
# cov2 = np.cov(p2, q2)
# print("Covariance matrix of p2 and q2:\n", cov2)

Product of p1 and q1:
 [[16 19]
 [26 31]]
Covariance matrix of p1 and q1:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


### (h) For the matrices x and y, find inner, outer and cartesian product:
x = np.array([[2, 3, 4], [3, 2, 9]])

y = np.array([[1, 5, 0], [5, 10, 3]])

In [9]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x, y)
outer = np.outer(x, y)
cartesian_product = np.array(np.meshgrid(x, y)).T.reshape(-1, 2)

print("Inner product:\n", inner)
print("Outer product:\n", outer)        
print("Cartesian product:\n", cartesian_product)

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


## Q2: Based on NumPy Mathematics and Statistics

### (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) 
i. Find element-wise absolute value 

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row 

In [10]:
array = np.array([[1, -2, 3],[-4, 5, -6]]) 

abs_array = np.abs(array)

percentile_flat = np.percentile(array, [25, 50, 75])
percentile_row = np.percentile(array, [25, 50, 75], axis=0)
percentile_col = np.percentile(array, [25, 50, 75], axis=1)

mean_flat = np.mean(array)
mean_row = np.mean(array, axis=1)
mean_col = np.mean(array, axis=0)

median_flat = np.median(array)
median_row = np.median(array, axis=1)
median_col = np.median(array, axis=0)

std_flat = np.std(array)
std_row = np.std(array, axis=1)
std_col = np.std(array, axis=0)

print("Absolute values:\n", abs_array)
print("Percentiles (flat):", percentile_flat)   
print("Percentiles (row-wise):\n", percentile_row)
print("Percentiles (column-wise):\n", percentile_col)
print("Mean (flat):", mean_flat)
print("Mean (row-wise):", mean_row)
print("Mean (column-wise):", mean_col)
print("Median (flat):", median_flat)
print("Median (row-wise):", median_row)
print("Median (column-wise):", median_col)
print("Standard Deviation (flat):", std_flat)
print("Standard Deviation (row-wise):", std_row)
print("Standard Deviation (column-wise):", std_col)

Absolute values:
 [[1 2 3]
 [4 5 6]]
Percentiles (flat): [-3.5 -0.5  2.5]
Percentiles (row-wise):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (column-wise):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean (flat): -0.5
Mean (row-wise): [ 0.66666667 -1.66666667]
Mean (column-wise): [-1.5  1.5 -1.5]
Median (flat): -0.5
Median (row-wise): [ 1. -4.]
Median (column-wise): [-1.5  1.5 -1.5]
Standard Deviation (flat): 3.8622100754188224
Standard Deviation (row-wise): [2.05480467 4.78423336]
Standard Deviation (column-wise): [2.5 3.5 4.5]


### (b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
Find floor, ceiling and truncated value, rounded values

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

floor_values = np.floor(a)
print("Floor values of the array:", floor_values)

ceil_values = np.ceil(a)
print("Ceil values of the array:", ceil_values)

truncated_values = np.trunc(a)
print("Truncated values of the array:", truncated_values)

rounded_values = np.round(a)
print("Rounded values of the array:", rounded_values)

Floor values of the array: [-2. -2. -1.  0.  1.  1.  3.]
Ceil values of the array: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values of the array: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values of the array: [-2. -2. -0.  0.  2.  2.  3.]


## Q3: Based on Searching and Sorting

### (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
i. Sorted array 

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements 

In [4]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

indicies_sorted = np.argsort(array)
print("Indices of sorted array:", indicies_sorted)

smallest_4 = np.partition(array, 4)[:4]
print("Smallest 4 elements:", smallest_4)

largest_5 = np.partition(array, -5)[-5:]
print("Largest 5 elements:", largest_5)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
Smallest 4 elements: [10 16 16 52]
Largest 5 elements: [ 16  52  54  62 453]


### (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 
i. Integer elements only 

ii. Float elements only

In [5]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

int_elements = array[array == array.astype(int)]
print("Integer elements in the array:", int_elements)

float_elements = array[array != array.astype(int)]
print("Float elements in the array:", float_elements)

Integer elements in the array: [1. 2. 3. 2.]
Float elements in the array: [1.2 2.2]


## Q4:

(a) Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images) 

In [15]:
from PIL import Image

def image_to_array(image_path):
    image = Image.open(image_path)
    image_array = np.array(image)
    
    if len(image_array.shape) == 2:
        np.savetxt("grayscale_image.txt", image_array, fmt='%d')
        print("Grayscale image saved as 'grayscale_image.txt'")
    else:
        reshaped_array = image_array.reshape(-1, image_array.shape[-1])
        np.savetxt("rgb.txt", reshaped_array, fmt='%d')
        print("RGB image saved as 'rgb.txt'")
    return image_array

image_path = r"C:\Users\bhana\Desktop\black-dog-gray-srgb.png"
image_array = image_to_array(image_path)

image_path = r"C:\Users\bhana\Desktop\030150da8ccb2469f5996061a561e490.jpg"
image_array = image_to_array(image_path)

Grayscale image saved as 'grayscale_image.txt'
RGB image saved as 'rgb.txt'


(b) Load the saved file into jupyter notebook.

In [16]:
try:
    grayscale_image = np.loadtxt("grayscale_image.txt", dtype=int)
    print("Grayscale image loaded successfully.\n", grayscale_image)
except FileNotFoundError:
    print("Grayscale image file not found. Please ensure the file exists.")
try:
    rgb_image = np.loadtxt("rgb.txt", dtype=int)
    print("RGB image loaded successfully.\n", rgb_image)
except FileNotFoundError:
    print("RGB image file not found. Please ensure the file exists.")

Grayscale image loaded successfully.
 [[43 65 65 ... 11 35  8]
 [29 43 65 ... 11  8 28]
 [34 29 43 ... 35  8 28]
 ...
 [43 43 65 ... 21 19 15]
 [43 43 43 ... 23 44 21]
 [43 43 43 ...  9 23 23]]
RGB image loaded successfully.
 [[248 240 191]
 [248 240 191]
 [247 239 190]
 ...
 [247 234 189]
 [247 234 189]
 [247 234 189]]
